### ISSUE TITLE
Building docker image on Raspberry Pi fails

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#495]
Running the local build script fails with this error:
`Step 4/12 : RUN npm ci
 ---> Running in 61ae24fd6ff5

> sodium-native@2.4.5 install /home/node/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

libtool is required, but wasn't found on this system
./configure: 5: ./configure: ./configure: not found
/home/node/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
             ^

Error: ./configure exited with 127
    at ChildProcess.<anonymous> (/home/node/node_modules/sodium-native/preinstall.js:149:25)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium-native@2.4.5 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium-native@2.4.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-16T19_14_55_435Z-debug.log
ERROR: Service 'testapi' failed to build: The command '/bin/sh -c npm ci' returned a non-zero code: 1`

**Comment by jzakotnik** [comment]
Used this command to build:
./scripts/local/start-master-node.sh

**Comment by jzakotnik** [comment]
This can be solved by downgrading the API image in the Dockerfile to node-8
