### ISSUE TITLE
If blockchain is restarting the api does not automatically connect to the new one

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#927]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

The api cannot reconnect to a restarted blockchain. So if the blockchain would shut down unexpectedly Trubudget is not working anymore.

### How to reproduce 🕹

I was using kubernetes but it's easy to reproduce locally:
1. start blockchain and api
2. restart blockchain container
3. For future requests against the api following error message occurs in api logs:
```
{"level":"fatal","time":1628844023188,"hostname":"api-prod-1-584c5db9d8-fdqrn","name":"TruBudget","error":{"code":-5,"message":"Invalid private key encoding"},"message":"BUG: Caught a non-Error type","v":1}
Trace
    at convertError (/home/node/dist/http_errors.js:23:17)
    at Array.map (<anonymous>)
    at Object.toHttpError (/home/node/dist/http_errors.js:8:31)
    at Object.<anonymous> (/home/node/dist/user_authenticate.js:182:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
The api is responding with:
```
{
  "apiVersion": "1.0",
  "error": {
      "code":500,
      "message":"Sorry, something went wrong :("
    }
}
```

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| API             | v1.24.0  |
| Blockchain      | v1.24.0  |

**Comment by Stezido** [comment]
This error happens if the blockchain hasn't persisted its data. So if the blockchain container is restarting and is starting a new blockchain master, it's intented that the api cannot connect to the new blockchain node. This way we prevent that the trubudget node can be silently exchanged. The api should always connect to the same node at least in the same session.

I will close this issue since the error message will be adapted in by solving #916
